import banner01 from '../images/banner01.svg'
import banner02 from '../images/banner02.svg'
import banner03 from '../images/banner03.svg'
import banner04 from '../images/banner04.svg'
import plate01 from '../images/plate_of_food_01.svg'
import plate02 from '../images/plate_of_food_02.svg'
import plate03 from '../images/plate_of_food_03.svg'
import plate04 from '../images/plate_of_food_04.svg'
import plate05 from '../images/plate_of_food_05.svg'
import plate06 from '../images/plate_of_food_06.svg'
import plate07 from '../images/plate_of_food_07.svg'
import backgroundPolygon from '../images/background_polygon.svg'
import backgroundContact from '../images/background_contact.svg'
import backgroundRectangle from '../images/background_rectangle.svg'

export { banner01, banner02, banner03, banner04, plate01, plate02, plate03, plate04, plate05, plate06, plate07, backgroundPolygon, backgroundContact, backgroundRectangle }
